const products = [
  {
    id: 1,
    name: "Hammer",
    category: "Tools",
    quantity: 50,
    supplier: "ToolMart",
    pricePerUnit: 1599,
    quantitySold: 30,
    dateAdded: "2023-01-10",
  },
  {
    id: 2,
    name: "Concrete Blocks",
    category: "Materials",
    quantity: 200,
    supplier: "Building Supply Co",
    pricePerUnit: 25,
    quantitySold: 150,
    dateAdded: "2022-12-05",
  },
  {
    id: 3,
    name: "Drill Set",
    category: "Tools",
    quantity: 30,
    supplier: "Hardware Emporium",
    pricePerUnit: 8999,
    quantitySold: 20,
    dateAdded: "2023-03-20",
  },
  {
    id: 4,
    name: "Wood Planks",
    category: "Materials",
    quantity: 150,
    supplier: "Timberland Supplies",
    pricePerUnit: 875,
    quantitySold: 100,
    dateAdded: "2022-11-28",
  },
  {
    id: 5,
    name: "Screwdriver Set",
    category: "Tools",
    quantity: 40,
    supplier: "Fix-It Tools",
    pricePerUnit: 195,
    quantitySold: 25,
    dateAdded: "2023-02-08",
  },
  {
    id: 20,
    name: "Circular Saw",
    category: "Tools",
    quantity: 20,
    supplier: "Cutting Edge Tools",
    pricePerUnit: 12999,
    quantitySold: 10,
    dateAdded: "2023-02-18",
  },
  {
    id: 21,
    name: 'Paint Rollers',
    category: 'Tools',
    quantity: 60,
    supplier: 'Paints & More',
    pricePerUnit: 575,
    quantitySold: 40,
    dateAdded: '2023-04-15',
  },
  {
    id: 22,
    name: 'Roofing Shingles',
    category: 'Materials',
    quantity: 300,
    supplier: 'Roofing Supplies Ltd',
    pricePerUnit: 1225,
    quantitySold: 200,
    dateAdded: '2023-03-28',
  },
  // Add more products similarly
  {
    id: 23,
    name: 'Welding Machine',
    category: 'Tools',
    quantity: 15,
    supplier: 'Welding World',
    pricePerUnit: 29999,
    quantitySold: 5,
    dateAdded: '2023-05-10',
  },
  {
    id: 24,
    name: 'Cement Bags',
    category: 'Materials',
    quantity: 100,
    supplier: 'Construction Depot',
    pricePerUnit: 899,
    quantitySold: 80,
    dateAdded: '2023-03-05',
  },
  {
    id: 30,
    name: 'Paintbrush Set',
    category: 'Tools',
    quantity: 25,
    supplier: 'Artisan Tools',
    pricePerUnit: 145,
    quantitySold: 15,
    dateAdded: '2023-05-20',
  },
];

export default products;
